### ISSUE TITLE
Generated TSV files cannot be imported into Postgres with transmart-copy due to missing headers in study.tsv

### ISSUE THREAD

**Issue by lukaszimmermann** [thehyve/python_transmart_loader#6]
When using the test input.json provided in the FHIR directory, the resulting TSV files cannot be imported with tranSMART Copy:

```
2019-04-03 09:39:10,378 [INFO] Deleting studies found in results ...
2019-04-03 09:39:10,470 [ERROR] Expected: [study_num, bio_experiment_id, study_id, secure_obj_token, study_blob]
2019-04-03 09:39:10,470 [ERROR] Was: [study_num, study_id, secure_obj_token]
2019-04-03 09:39:10,481 [ERROR] Incorrect headers in file i2b2demodata/study.tsv.
java.lang.IllegalStateException: Incorrect headers in file i2b2demodata/study.tsv.
	at org.transmartproject.copy.Util.verifyHeader(Util.groovy:60)
	at org.transmartproject.copy.table.Studies$_delete_closure3$_closure8.doCall(Studies.groovy:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1946)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1926)
	at org.transmartproject.copy.table.Studies$_delete_closure3.doCall(Studies.groovy:216)
	at org.transmartproject.copy.table.Studies$_delete_closure3.call(Studies.groovy)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withReader(IOGroovyMethods.java:1183)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withReader(ResourceGroovyMethods.java:1604)
	at org.transmartproject.copy.table.Studies.delete(Studies.groovy:214)
	at org.transmartproject.copy.Copy.deleteStudy(Copy.groovy:155)
	at org.transmartproject.copy.Copy.runCopy(Copy.groovy:222)
	at org.transmartproject.copy.Copy.main(Copy.groovy:167)
```

The following headers are missing in the `study.tsv` file:
 * bio_experiment_id
 * study_blob

**Comment by gijskant** [comment]
Since release [17.1-HYVE-5.9](https://github.com/thehyve/transmart-core/releases/tag/v17.1-hyve-5.9), it is possible to [leave out nullable columns from transmart-copy input files](https://github.com/thehyve/transmart-core/commit/6477fb91bb281ab5057b398764b6e029252451af#diff-f9c6aaeac385cf3bd68ee76e91eb4180).
When you fetch that version of transmart-copy, it should work.
